# - name: Update walkthrough location
#   set_fact:
#     webapp_walkthrough_locations: "{{ webapp_walkthrough_locations }}"
#   # when: datasync | bool | default(true)

- name: Construct openshift host string
  shell: echo {{ openshift_master_public_url | default(openshift_asset_url, true) }} | cut -d '/' -f3
  register: openshift_host

- name: Construct openshift oauth string
  shell: echo {{ openshift_master_url | replace('https://', '') }} | cut -d '/' -f1
  register: openshift_oauth_host

- name: Get SSO route
  shell: oc get route sso -o template --template \{\{.spec.host\}\} -n {{ eval_rhsso_namespace }}
  register: sso_route

- name: Add additional walkthrough locations in the default list
  set_fact:
    webapp_walkthrough_locations: "{{ webapp_walkthrough_locations + [datasync_walkthrough_location] }}"
  when: datasync | bool | default(true)

- name: Generate WebApp custom resource template
  template:
    force: yes
    src: "cr.yaml.j2"
    dest: /tmp/webapp-cr.yml

- name: Create WebApp custom resource
  shell: oc apply -f /tmp/webapp-cr.yml -n {{ webapp_namespace }}
  register: create_webapp_custom_resource_cmd
  failed_when: create_webapp_custom_resource_cmd.stderr != '' and 'AlreadyExists' not in create_webapp_custom_resource_cmd.stderr
  changed_when: create_webapp_custom_resource_cmd.rc == 0


- name: Wait for pods
  shell: sleep 5; oc get pods --namespace {{ webapp_namespace }}  |  grep  "Creating"
  register: result
  until: not result.stdout
  retries: 100
  delay: 10
  failed_when: result.stdout
  changed_when: False

# - name: Set webapp env var
  # shell: "oc set env \
  # dc/tutorial-web-app \
  # 'OPTIONAL_PROVISION_SERVICES={{ webapp_provision_services|join(',') }}' \
  # 'OPTIONAL_WATCH_SERVICES={{ webapp_watch_services|join(',') }}' \
  # -n {{ webapp_namespace }}"
  # when: webapp_provision_services|length > 0 or webapp_watch_services|length > 0
